# Generated by Django 6.0.6 on 2026-06-16 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_productdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='Category_Name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='productdb',
            old_name='Description',
            new_name='description',
        ),
    ]
